### PR TITLE
Add docker image for server

### PR DESCRIPTION
**Pull request by carlostighe**
Add docker image for server and add running instructions to readme.

### CODE REVIEW

**Comment by andrewcottam** [comment]
Thanks a lot Carlos! I look forward to trying this next week.

**Comment by andrewcottam** [comment]
Hi Carlos - would we be able to deploy the image to hub.docker.com too? If so, is that something you would be able to do? I had a question from one of our partners in the Pacific.

**Comment by carlostighe** [comment]
Hi @andrewcottam 
Yes I can deploy the images to dockerhub. 
Ill try to get to it today.

**Comment by carlostighe** [comment]
Hey Andrew,

I have pushed images to dockerhub

https://hub.docker.com/repository/docker/craicerjack/marxan-server  

https://hub.docker.com/repository/docker/craicerjack/marxan-client  

But the server image fails to run if it doesnt have a local database to connect to.

**Comment by andrewcottam** [comment]
Great! Thanks a lot Carlos.

**Pull request merged**
